import currency from "../models/admin/currency.js";
import mongoose from "mongoose";

const currencyData = [
    {
        country: "United States of America",
        name: "United States Dollar",
        code: "USD",
        symbol: "$",
    },
    {
        country: "Eurozone countries",
        name: "Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Japan",
        name: "Japanese Yen ",
        code: "JPY",
        symbol: "¥",
    },
    {
        country: "United Kingdom",
        name: "British Pound",
        code: "GBP",
        symbol: "£",
    },
    {
        country: "Australia",
        name: "Australian Dollar",
        code: "AUD",
        symbol: "A$",
    },
    {
        country: "Canada",
        name: "Canadian Dollar ",
        code: "CAD",
        symbol: "CA$",
    },
    {
        country: "Switzerland",
        name: "Swiss Franc",
        code: "CHF",
        symbol: "CHF",
    },
    {
        country: "China",
        name: "Chinese Yuan",
        code: "CNY",
        symbol: "¥",
    },
    {
        country: "Sweden",
        name: "Swedish Krona ",
        code: "SEK",
        symbol: "kr",
    },
    {
        country: "New Zealand",
        name: "New Zealand Dollar ",
        code: "NZD",
        symbol: "NZ$",
    },
    {
        country: "India",
        name: "Indian Rupee",
        code: "INR",
        symbol: "₹",
    },
    {
        country: "Brazil",
        name: "Brazilian Real",
        code: "BRL",
        symbol: "R$",
    },
    {
        country: "Russia",
        name: "Russian Ruble",
        code: "RUB",
        symbol: "₽",
    },
    {
        country: "South Africa",
        name: "South African Rand",
        code: "ZAR",
        symbol: "R",
    },
    {
        country: "Mexico",
        name: "Mexican Peso",
        code: "MXN",
        symbol: "Mex$",
    },
    {
        country: "Singapore",
        name: "Singapore Dollar",
        code: "SGD",
        symbol: "S$",
    },
    {
        country: "Norway",
        name: "Norwegian Krone",
        code: "NOK",
        symbol: "kr",
    },
    {
        country: "Denmark",
        name: "Danish Krone",
        code: "DKK",
        symbol: "kr",
    },
    {
        country: "Hong Kong",
        name: "Hong Kong Dollar",
        code: "HKD",
        symbol: "HK$",
    },
    {
        country: "South Korea",
        name: "South Korean Won",
        code: "KRW",
        symbol: "₩",
    },
    {
        country: "United Arab Emirates",
        name: "United Arab Emirates Dirham",
        code: "AED",
        symbol: "د.إ",
    },
    {
        country: "Turkey",
        name: "Turkish Lira",
        code: "TRY",
        symbol: "₺",
    },
    {
        country: "Argentina",
        name: "Argentine Peso",
        code: "ARS",
        symbol: "$",
    },
    {
        country: "Thailand",
        name: "Thai Baht",
        code: "THB",
        symbol: "฿",
    },
    {
        country: "Malaysia",
        name: "Malaysian Ringgit",
        code: "MYR",
        symbol: "RM",
    },
    {
        country: "Indonesia",
        name: "Indonesian Rupiah",
        code: "IDR",
        symbol: "Rp",
    },
    {
        country: "Philippines",
        name: "Philippine Peso",
        code: "PHP",
        symbol: "₱",
    },
    {
        country: "Egypt",
        name: "Egyptian Pound",
        code: "EGP",
        symbol: "E£",
    },
    {
        country: "Nigeria",
        name: "Nigerian Naira",
        code: "NGN",
        symbol: "₦",
    },
    {
        country: "Israel",
        name: "Israeli New Shekel",
        code: "ILS",
        symbol: "₪",
    },
    {
        country: "Poland",
        name: "Polish Złoty",
        code: "PLN",
        symbol: "zł",
    },
    {
        country: "Hungary",
        name: "Hungarian Forint",
        code: "HUF",
        symbol: "Ft",
    },
    {
        country: "Czech Republic",
        name: "Czech Koruna",
        code: "CZK",
        symbol: "Kč",
    },
    {
        country: "Croatia",
        name: "Croatian Kuna",
        code: "HRK",
        symbol: "kn",
    },
    {
        country: "Romania",
        name: "Romanian Leu",
        code: "RON",
        symbol: "lei",
    },
    {
        country: "Bulgaria",
        name: "Bulgarian Lev",
        code: "BGN",
        symbol: "лв",
    },
    {
        country: "Austria",
        name: "Austrian Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Iceland",
        name: "Icelandic Króna",
        code: "ISK",
        symbol: "kr",
    },
    {
        country: "Finland",
        name: "Finnish Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Estonia",
        name: "Estonian Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Latvia",
        name: "Latvian Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Lithuania",
        name: "Lithuanian Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Slovakia",
        name: "Slovak Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Slovenia",
        name: "Slovenian Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Luxembourg",
        name: "Luxembourgish Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Netherlands",
        name: "Dutch Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Belgium",
        name: "Belgian Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "France",
        name: "French Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Germany",
        name: "German Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Italy",
        name: "Italian Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Portugal",
        name: "Portuguese Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Spain",
        name: "Spanish Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Ireland",
        name: "Irish Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Greece",
        name: "Greek Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Cyprus",
        name: "Cypriot Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Malta",
        name: "Maltese Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Lichtenstein",
        name: "Liechtenstein Franc",
        code: "CHF",
        symbol: "CHF",
    },
    {
        country: "Monaco",
        name: "Monaco Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "San Marino",
        name: "San Marino Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Vatican City",
        name: "Vatican City Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Andorra",
        name: "Andorran Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Montenegro",
        name: "Montenegrin Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Serbia",
        name: "Serbian Dinar",
        code: "RSD",
        symbol: "дин.",
    },
    {
        country: "Macedonia",
        name: "Macedonian Denar",
        code: "MKD",
        symbol: "ден",
    },
    {
        country: "Albania",
        name: "Albanian Lek",
        code: "ALL",
        symbol: "L",
    },
    {
        country: "Bosnia and Herzegovina",
        name: "Bosnia and Herzegovina Convertible Marka",
        code: "BAM",
        symbol: "KM",
    },
    {
        country: "Kosovo",
        name: "Kosovar Euro",
        code: "EUR",
        symbol: "€",
    },
    {
        country: "Moldova",
        name: "Moldovan Leu",
        code: "MDL",
        symbol: "MDL",
    },
    {
        country: "Ukraine",
        name: "Ukrainian Hryvnia",
        code: "UAH",
        symbol: "₴",
    },
    {
        country: "Belarus",
        name: "Belarusian Ruble",
        code: "BYN",
        symbol: "Br",
    },
    {
        country: "Armenia",
        name: "Armenian Dram",
        code: "AMD",
        symbol: "֏",
    },
    {
        country: "Azerbaijan",
        name: "Azerbaijani Manat",
        code: "AZN",
        symbol: "₼",
    },
    {
        country: "Georgia",
        name: "Georgian Lari",
        code: "GEL",
        symbol: "₾",
    },
    {
        country: "Kazakhstan",
        name: "Kazakhstani Tenge ",
        code: "KZT",
        symbol: "₸",
    },
    {
        country: "Kyrgyzstan",
        name: "Kyrgyzstani Som",
        code: "KGS",
        symbol: "сом",
    },
    {
        country: "Tajikistan",
        name: "Tajikistani Somoni",
        code: "TJS",
        symbol: "ЅМ",
    },
    {
        country: "Turkmenistan",
        name: "Turkmenistani Manat",
        code: "TMT",
        symbol: "T",
    },
    {
        country: "Uzbekistan",
        name: "Uzbekistani Som",
        code: "UZS",
        symbol: "so'm",
    },
    {
        country: "Afghanistan",
        name: "Afghan Afghani",
        code: "AFN",
        symbol: "؋",
    },
    {
        country: "Iran",
        name: "Iranian Rial",
        code: "IRR",
        symbol: "﷼",
    },
    {
        country: "Iraq",
        name: "Iraqi Dinar",
        code: "IQD",
        symbol: "ع.د",
    },
    {
        country: "Syria",
        name: "Syrian Pound",
        code: "SYP",
        symbol: "£",
    },
    {
        country: "Lebanon",
        name: "Lebanese Pound",
        code: "LBP",
        symbol: "ل.ل",
    },
    {
        country: "Jordan",
        name: "Jordanian Dinar",
        code: "JOD",
        symbol: "د.ا",
    },
    {
        country: "Palestine",
        name: "Palestinian Shekel",
        code: "ILS",
        symbol: "₪",
    },
    {
        country: "Saudi Arabia",
        name: "Saudi Riyal",
        code: "SAR",
        symbol: "﷼",
    },
    {
        country: "Yemen",
        name: "Yemeni Rial",
        code: "YER",
        symbol: "﷼",
    },
    {
        country: "Oman",
        name: "Omani Rial",
        code: "OMR",
        symbol: "﷼",
    },
    {
        country: "Qatar",
        name: "Qatari Riyal",
        code: "QAR",
        symbol: "﷼",
    },
    {
        country: "Bahrain",
        name: "Bahraini Dinar",
        code: "BHD",
        symbol: ".د.ب",
    },
    {
        country: "Kuwait",
        name: "Kuwaiti Dinar",
        code: "KWD",
        symbol: "د.ك",
    },
    {
        country: "Uganda",
        name: "Ugandan Shilling",
        code: "UGX",
        symbol: "USh",
    },
    {
        country: "Kenya",
        name: "Kenyan Shilling",
        code: "KES",
        symbol: "KSh",
    },
    {
        country: "Tanzania",
        name: "Tanzanian Shilling",
        code: "TZS",
        symbol: "TSh",
    },
    {
        country: "Rwanda",
        name: "Rwandan Franc",
        code: "RWF",
        symbol: "RF",
    },
    {
        country: "Burundi",
        name: "Burundian Franc",
        code: "BIF",
        symbol: "FBu",
    },
    {
        country: "South Sudan",
        name: "South Sudanese Pound",
        code: "SSP",
        symbol: "SSP",
    },
    {
        country: "Sudan",
        name: "Sudanese Pound",
        code: "SDG",
        symbol: "SDG",
    },
    {
        country: "Ethiopia",
        name: "Ethiopian Birr",
        code: "ETB",
        symbol: "Br",
    },
    {
        country: "Eritrea",
        name: "Eritrean Nakfa",
        code: "ERN",
        symbol: "Nfk",
    },
    {
        country: "Djibouti",
        name: "Djiboutian Franc",
        code: "DJF",
        symbol: "Fdj",
    },
    {
        country: "Somalia",
        name: "Somali Shilling",
        code: "SOS",
        symbol: "S",
    },
    {
        country: "Comoros",
        name: "Comorian Franc",
        code: "KMF",
        symbol: "CF",
    },
    {
        country: "Mauritius",
        name: "Mauritian Rupee",
        code: "MUR",
        symbol: "₨",
    },
    {
        country: "Seychelles",
        name: "Seychellois Rupee",
        code: "SCR",
        symbol: "₨",
    },
    {
        country: "Madagascar",
        name: "Malagasy Ariary",
        code: "MGA",
        symbol: "Ar",
    },
    {
        country: "Malawi",
        name: "Malawian Kwacha",
        code: "MWK",
        symbol: "MK",
    },
    {
        country: "Zambia",
        name: "Zambian Kwacha",
        code: "ZMW",
        symbol: "ZK",
    },
    {
        country: "Zimbabwe",
        name: "Zimbabwean Dollar",
        code: "ZWL",
        symbol: "Z$",
    },
    {
        country: "Botswana",
        name: "Botswana Pula",
        code: "BWP",
        symbol: "P",
    },
    {
        country: "Namibia",
        name: "Namibian Dollar",
        code: "NAD",
        symbol: "N$",
    },
    {
        country: "Lesotho",
        name: "Lesotho Loti",
        code: "LSL",
        symbol: "M",
    },
    {
        country: "Eswatini",
        name: "Swazi Lilangeni",
        code: "SZL",
        symbol: "E",
    },
    {
        country: "Angola",
        name: "Angolan Kwanza",
        code: "AOA",
        symbol: "Kz",
    },
    {
        country: "Mozambique",
        name: "Mozambican Metical",
        code: "MZN",
        symbol: "MT",
    },
    {
        country: "Maldives",
        name: "Maldivian Rufiyaa",
        code: "MVR",
        symbol: "ރ.",
    },
    {
        country: "Nepal",
        name: "Nepalese Rupee",
        code: "NPR",
        symbol: "रू",
    },
    {
        country: "Bhutan",
        name: "Bhutanese Ngultrum",
        code: "BTN",
        symbol: "Nu.",
    },
    {
        country: "Bangladesh",
        name: "Bangladeshi Taka",
        code: "BDT",
        symbol: "৳",
    },
    {
        country: "Pakistan",
        name: "Pakistani Rupee",
        code: "PKR",
        symbol: "₨",
    },
    {
        country: "Sri Lanka",
        name: "Sri Lankan Rupee",
        code: "LKR",
        symbol: "Rs",
    },
];

async function seedCurrencies() {
    try {
        for (const curr of currencyData) {
            const existingCurrency = await currency.findOne({ code: curr.code });
            if (!existingCurrency) {
              await currency.create(curr);
            } else {
              return
            }
          }
    } catch (error) {
        throw new Error(error);
    }
}

export default seedCurrencies;