name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork
      uses: actions/checkout@v3
      with:
        ref: development # Ensure you're working on the correct base branch

    - name: Add Upstream
      run: |
        git remote add upstream https://github.com/Techfriar/workfriar_backend.git
        git fetch upstream

    - name: Check for Merge Conflicts
      run: |
        git merge --no-commit --no-ff upstream/development || echo "Merge conflicts detected" && exit 1
      continue-on-error: false

    - name: Merge and Push Changes
      if: success() # Only proceed if no conflicts are detected
      run: |
        git merge upstream/development --no-edit
        git push origin development
